### PR TITLE
Add the possibility to whitelist a list of paths

### PR DESCRIPTION
**Pull request by fistons**
This PR add the possibility to configure a list of paths that will be ignore by the rate limiter

### CODE REVIEW

**Comment by AaronErhardt** [comment]
Looks good but I wonder whether an alternative to whitelisting would be to not use the middleware for some requests handlers. IIRC you can register request handlers before adding a middleware or group them to avoid having them rate-limited. That would probably be a better solution if that works for you.

**Comment by fistons** [comment]
I may indeed miss something in my understanding of the actix middlewares. Since it's not the place to discuss this, I will update my issue https://github.com/AaronErhardt/actix-governor/issues/40 with my use case

**Comment by AaronErhardt** [comment]
With the issue now closed, do you still have interest in merging this or should we close this as well?

**Comment by fistons** [comment]
I think we can close it indeed, as I found a perfect solution for my use case.

Thanks (and cool profile pics by the way, I want the same plush)

**Pull request closed without merging**
